---
spring:
  profiles: cloud-eureka-server1
server:
  port: 8761
eureka:
  instance:
    hostname: cloud-eureka-server1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://cloud-eureka-server2:8762/eureka/
---
spring:
  profiles: cloud-eureka-server2
server:
  port: 8762
eureka:
  instance:
    hostname: cloud-eureka-server2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://cloud-eureka-server1:8761/eureka/
---
spring:
  profiles: cloud-eureka-server3
server:
  port: 8763
eureka:
  instance:
    hostname: cloud-eureka-server3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://cloud-eureka-server1:8761/eureka/,http://cloud-eureka-server2:8762/eureka/